### ISSUE TITLE
reduction of content

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/biocasia2020_tidytranscriptomics#1]
Hello @mblue9 here we go with the next! XD

We need to get from 3 to 1 hour between bulk and single-cell.

**Comment by mblue9** [comment]
Easy ;)
Well maybe, initial thoughts are
Move to supplementary (or omit)
-Background - just put the 2 workflow images in the main material 
-Part 2 - can just say multiple RNA-seq tools can be used (or include a really short version of it)
-Drop Pasilla

**Comment by stemangiola** [comment]
Yes, we can drop some aspects of the initial bulk study. I think it would be worth to show at least the pvalue comparison from the DE comparison, as it is an unresolved issue in the community (absence of integrative software)

**Comment by mblue9** [comment]
I've started editing the content, noticed Seurat is still discussed in the Part 2 will you be removing that?
Do we need tidyseurat package aswell or should we remove?
Can you make a tagged release for tidySCE with the new changes e.g. v0.99.1 if that's what we're going to use? & then we can set the github actions file to use that here.

**Comment by mblue9** [comment]
Also can you enable the github pages again here, thanks :)

**Comment by stemangiola** [comment]
We don't have the pages branch yet..

**Comment by stemangiola** [comment]
> Do we need tidyseurat package aswell or should we remove?

We can remove, I might have missed some mentions to that package in the conversion process.



> Can you make a tagged release for tidySCE with the new changes e.g. v0.99.1

Sure, we might use the master, as the review branch will give errors I imagine, plus most changes there are internal styling

**Comment by stemangiola** [comment]
A thought about prioritizing content in order to decrease time.

tidybulk currently has 20 subsections, tidySCE has 10. We should probably making them more balanced.

For tidybulk

- do we need the part about gene annotation
- we could show directly the multi-method DE analysis, and chose one method for the plots
- for deconvolution we might mention the funny twitter reply and take the survival analysis off
- do we need ADD vs GET?

**Comment by mblue9** [comment]
>We don't have the pages branch yet.

Ah yes forgot we need one actions to pass first

>We can remove, I might have missed some mentions to that package in the conversion process.
> Sure, we might use the master, as the review branch will give errors I imagine, plus most changes there are internal styling 

Ok cool, should we make a tagged release for master e.g. 0.99.0? as at the moment the install instructions [here](https://github.com/stemangiola/biocasia2020_tidytranscriptomics#via-github) say use these versions to have the same versions in the workshop and master will change?

>A thought about prioritizing content in order to decrease time.

>tidybulk currently has 20 subsections, tidySCE has 10. We should probably making them more balanced.

Yes agree we need to cut more this was just a start

>For tidybulk

>do we need the part about gene annotation

we don't need it as a separate section, I could add it into the "setting up data" section and just say we can shorten sample ids and add gene symbols and move on.

>we could show directly the multi-method DE analysis, and chose one method for the plots

yep so just show p values comparison and not logFC aswell? what do you mean by "show directly"?

> for deconvolution we might mention the funny twitter reply and take the survival analysis off

ok

>do we need ADD vs GET?

no I don't think so I was going to ask you about that

**Comment by stemangiola** [comment]
> Ok cool, should we make a tagged release for master e.g. 0.99.0?

done

> yep so just show p values comparison and not logFC aswell? what do you mean by "show directly"?

just pvalues is good. I mean instead of doing DE part, and then multi-method DE. We could start with multi-method DE, and then keep a method to do the MA plots etc..

**Comment by mblue9** [comment]
>  I mean instead of doing DE part, and then multi-method DE. We could start with multi-method DE, and then keep a method to do the MA plots etc..

Ah ok yes that could be good, lets try that.

**Comment by stemangiola** [comment]
I'm not even sure we need tidygate

**Comment by mblue9** [comment]
>I'm not even sure we need tidygate

yep agree I already removed tidygate as I don't think we have time.

**Comment by mblue9** [comment]
I've made all those changes discussed so far here https://github.com/stemangiola/biocasia2020_tidytranscriptomics/pull/3

**Comment by mblue9** [comment]
I removed get_bibliography for the moment for time and as it doesn't show the ref for voom, and not sure if it should have the refs for the specific edgeR methods (from the edgeR user guide)?
>The glm functions can test for differential expression using either likelihood
ratio tests[25, 3] or quasi-likelihood F-tests [23, 22].

but we can put it back in if you like.

**Comment by stemangiola** [comment]
> I removed get_bibliography

get_bibliography is a great tool! I recon that's alone a reason to use tidybulk.

**Comment by mblue9** [comment]
Ok I'll put it back 👍 

If there's time I'll try to add those refs to tidybulk then.

**Comment by stemangiola** [comment]
> it doesn't show the ref for voom, and not sure if it should have the refs for the specific edgeR methods

I open an issue on tidybulk. We should show the function, and curated a bit in the near future. I will try to improve.

https://github.com/stemangiola/tidybulk/issues/121

**Comment by mblue9** [comment]
Content has been reduced ✅
