### ISSUE TITLE
plotly for volcano plot

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/biocasia2020_tidytranscriptomics#5]
I am aware that users asked at te last workshop, adding is a good idea. However,

- for some reason plotly does not secognise point size
- with no surprise ggrepel does not get included (maybe we can use geom_text() instead)
- the plot bacomes heavy and the scrolling hangs

**Comment by mblue9** [comment]
Yeah I wasn’t sure about this, I was mainly trying it to see if it could save some time by not doing stripcharts aswell. But I’ll remove the interactive bit here & put the stripcharts back.

**Comment by stemangiola** [comment]
> Yeah I wasn’t sure about this, I was mainly trying it to see if it could save some time by not doing stripcharts aswell.

I'd like this. Plotly has such bad performance with a lot of points.

**Comment by mblue9** [comment]
Added back here https://github.com/stemangiola/biocasia2020_tidytranscriptomics/commit/93093b27bc809bfaa0b718dd10dab2aad13c8949
