### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/biocasia2020_tidytranscriptomics#6]
Hello @mblue9 , do I need to do something for the docker creation?

**Comment by mblue9** [comment]
Can you add the Docker secrets if you haven't already?
Then we need to uncomment the docker build in the .github file. But that will slow down any final edits we make so just before we do that -  are you happy with the material as is? There are currently 3 polls in Part 1 and no polls in Part 2 is that ok with you?

**Comment by stemangiola** [comment]
> Can you add the Docker secrets if you haven't already?

I added them, I just forgot that we have deactivated the docker for testing :)

Can we briefly meet, just so we are on the same page on this version of the workshop?

**Comment by mblue9** [comment]
Yep lets do it.

**Comment by stemangiola** [comment]
Cool I'm here

https://unimelb.zoom.us/j/6941487048?pwd=dE1vb3RQb01xUWFXbEpFYWFoZGR4dz09

**Comment by stemangiola** [comment]
Sorry! I;m in my usual room.

https://unimelb.zoom.us/j/2488420862?pwd=SEFYN1JSWWJXT2NMbHhFY1lCRDBPQT09

**Comment by mblue9** [comment]
Docker turned on here https://github.com/stemangiola/biocasia2020_tidytranscriptomics/commit/c0459dd0e03d882fd88e04621d0b72c6d13efae8
