### ISSUE TITLE
update pbmc object as singlecellexperiment, now is tidy already

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/biocasia2020_tidytranscriptomics#9]

**Comment by mblue9** [comment]
Do you need to fix this for the workshop or ok to mention and fix after? If you need to fix for workshop you could risk it but need to do it quick as takes >1hr to run the actions.

**Comment by stemangiola** [comment]
I found a solution for now. no prob. It just we want to freeze this workshop in a good shape before is never touched again.

We can resolve after the workshop :)

**Comment by mblue9** [comment]
ok phew... last minute changes would be risky :)

**Comment by stemangiola** [comment]
another change 

```
pbmc_small_polished_abundance %>%
  ggplot2::ggplot(aes(groups, abundance_counts + 1, fill=groups)) +
  geom_boxplot(outlier.shape=NA) +
  geom_jitter(alpha=0.5, width=0.2) +
  scale_y_log10() +
  facet_wrap(~transcript, scales="free_y") +
  custom_theme
```

**Comment by stemangiola** [comment]
another change

all packages used as comments next to functions
